"""
10_prompt_caching.py — pay once, read cheap.

Concepts:
  REQUEST  :
    Add cache_control={"type": "ephemeral"} either:
      a) top-level on messages.create — auto-caches the last cacheable block
      b) on a specific block (system text block, tool definition, message block)
    The prefix up to and including that block gets cached.

  RESPONSE :
    response.usage carries two new fields:
      cache_creation_input_tokens — tokens WRITTEN to cache this request (~1.25x cost)
      cache_read_input_tokens     — tokens SERVED from cache this request (~0.1x cost)
      input_tokens                — remaining uncached input (full price)

Mechanics:
  - Cache is a PREFIX MATCH. Any byte change anywhere in the prefix invalidates
    the cache. Render order is `tools` → `system` → `messages`.
  - Default TTL: 5 minutes. Add "ttl": "1h" for one-hour caching (write cost
    is 2x instead of 1.25x; break-even requires more hits).
  - Minimum cacheable prefix on Opus 4.8 is ~4096 tokens. Shorter prefixes
    silently won't cache (no error, just cache_creation_input_tokens=0).
  - Max 4 cache_control breakpoints per request.

This script:
  Sends the SAME large system prompt twice and prints the usage telemetry
  for each request. Run #1 writes the cache; run #2 reads it.
"""
import time

from _common import client, MODEL, section, dump


# ============================================================
#  Build a system prompt large enough to clear the 4096-token minimum
# ============================================================
# We pack a synthetic "reference document" so the prompt is well over the
# Opus 4.8 minimum (4096 tokens). The content is intentionally boring so
# the test stays deterministic.
LOREM = (
    "The Common Lisp HyperSpec, generated by Kent Pitman, was a HyperSpec "
    "derivative of the ANSI Common Lisp standard. It documents every "
    "function, macro, and special operator. Lisp's S-expression syntax "
    "treats code and data uniformly, enabling powerful metaprogramming. "
)
big_doc = LOREM * 250    # ~3500 words → well over the 4096-token floor
print(f"Reference doc length: {len(big_doc):,} chars")


system = [
    {
        "type": "text",
        "text": "You answer questions strictly from the REFERENCE DOCUMENT below.",
    },
    {
        "type": "text",
        "text": f"REFERENCE DOCUMENT:\n{big_doc}",
        "cache_control": {"type": "ephemeral"},  # cache up to here
    },
]


def run(label: str, user_q: str) -> None:
    section(label)
    r = client.messages.create(
        model=MODEL,
        max_tokens=128,
        system=system,
        messages=[{"role": "user", "content": user_q}],
    )
    u = r.usage
    print(f"input_tokens                  : {u.input_tokens:>6}   (uncached, full price)")
    print(f"cache_creation_input_tokens   : {u.cache_creation_input_tokens:>6}   (written to cache, ~1.25x)")
    print(f"cache_read_input_tokens       : {u.cache_read_input_tokens:>6}   (served from cache, ~0.1x)")
    print(f"output_tokens                 : {u.output_tokens:>6}")
    print(f"\nanswer: {r.content[0].text}")


# ============================================================
#  Run 1 — cache MISS (the cache gets WRITTEN)
# ============================================================
run("RUN 1 — cold cache (expect cache_creation > 0, cache_read = 0)",
    "What does the HyperSpec document?")

# Brief pause — cache becomes readable shortly after the first response begins
# streaming. For sequential requests like this, we're fine immediately.
time.sleep(1)


# ============================================================
#  Run 2 — cache HIT (the cache gets READ)
# ============================================================
# Same system prompt, different user question. The system+tools prefix is
# identical so the cached prefix matches and gets read.
run("RUN 2 — warm cache (expect cache_read > 0, cache_creation = 0)",
    "Why is S-expression syntax mentioned as useful?")


# ============================================================
#  Common pitfalls
# ============================================================
section("CACHING PITFALLS")
print("""\
A surprising number of caching bugs trace back to ONE BYTE of variation in
the prefix. Things to never do:

  • Interpolate datetime.now()  / uuid4() into the system prompt.
  • Use json.dumps(d) without sort_keys=True — dict order varies.
  • Change the tools array per user/session — tools render at offset 0,
    invalidating everything.
  • Switch models mid-conversation — caches are model-scoped.

To debug a missing cache hit:
  1. Print usage.cache_read_input_tokens. Zero means a miss.
  2. Diff the two rendered request bodies (tools + system + messages) byte
     for byte. The first differing byte is the invalidator.
""")
