"""
10_prompt_caching.py — automatic prompt caching on the Responses API.

Key differences from Anthropic's prompt caching:

  | Aspect        | Anthropic                       | OpenAI                              |
  |---------------|--------------------------------|--------------------------------------|
  | Opt-in        | Explicit cache_control marker  | Automatic — no opt-in needed         |
  | Trigger size  | ≥ 4096 tokens (Opus 4.8)       | ≥ 1024 tokens                        |
  | Granularity   | Up to 4 breakpoints per request| Prefix-only (whole prefix is cached) |
  | Telemetry     | usage.cache_read_input_tokens  | usage.input_tokens_details.cached_tokens |
  | Pricing       | Read ≈ 0.1× / Write ≈ 1.25×    | Read ≈ 0.5× / Write = normal price   |
  | TTL           | 5 min default; 1 h optional    | ~5 min (subject to load)             |
  | Key           | Implicit (prefix hash)         | Implicit prefix hash; can pass         |
  |               |                                | `prompt_cache_key` for session affinity |

OpenAI caches the input prefix automatically. To MAXIMIZE hits:
  1. Keep volatile content (timestamps, per-user IDs) at the END of input.
  2. Pass `prompt_cache_key` to bind related requests to the same cache slot
     (useful when many users hit the same prefix; routes them consistently).

This script sends the same large input twice and prints
`usage.input_tokens_details.cached_tokens` to show the cache hit.
"""
import time

from _common import client, MODEL, section, dump


# ============================================================
#  Build a large stable prefix
# ============================================================
LOREM = (
    "The Common Lisp HyperSpec, generated by Kent Pitman, was a HyperSpec "
    "derivative of the ANSI Common Lisp standard. It documents every "
    "function, macro, and special operator. Lisp's S-expression syntax "
    "treats code and data uniformly, enabling powerful metaprogramming. "
)
big_doc = LOREM * 250         # ~3500 words → well over the 1024-token minimum
print(f"Reference doc length: {len(big_doc):,} chars")


# Use instructions to carry the large stable prefix, and put the per-request
# question in `input` to maximize what's reusable across calls.
instructions = (
    "You answer questions strictly from the REFERENCE DOCUMENT below.\n\n"
    f"REFERENCE DOCUMENT:\n{big_doc}"
)


def run(label: str, question: str) -> None:
    section(label)
    r = client.responses.create(
        model=MODEL,
        instructions=instructions,
        input=question,
        # Optional — pin requests with the same prefix to the same cache slot:
        prompt_cache_key="hyperspec-study-v1",
        reasoning={"effort": "none"},      # gpt-5.6: "minimal" was removed; "none" = zero reasoning tokens
    )
    u = r.usage
    print(f"input_tokens                              : {u.input_tokens}")
    print(f"input_tokens_details.cached_tokens        : {u.input_tokens_details.cached_tokens}")
    print(f"output_tokens                             : {u.output_tokens}")
    print(f"output_tokens_details.reasoning_tokens    : {u.output_tokens_details.reasoning_tokens}")
    pct = (u.input_tokens_details.cached_tokens / u.input_tokens * 100) if u.input_tokens else 0
    print(f"cache hit rate                            : {pct:.1f}%")
    print(f"\nanswer: {r.output_text}")


# ============================================================
#  Run 1 — cold cache (cached_tokens should be 0)
# ============================================================
run("RUN 1 — cold cache (expect cached_tokens = 0)",
    "What does the HyperSpec document?")

time.sleep(1)


# ============================================================
#  Run 2 — warm cache (cached_tokens should be > 0)
# ============================================================
# Same instructions prefix, different user question.
run("RUN 2 — warm cache (expect cached_tokens > 0)",
    "Why is S-expression syntax mentioned as useful?")


# ============================================================
#  Common invalidators
# ============================================================
section("CACHING TIPS")
print("""\
Caches the longest matching PREFIX. To maximize hits:

  ✓ Put stable content first (instructions, system prompt, reference docs).
  ✓ Put volatile content last (per-user question, current time).
  ✓ Use prompt_cache_key to keep related requests on the same cache slot.

Silent invalidators:
  ✗ Embedding the current time / UUIDs in `instructions`.
  ✗ Changing the `tools` array between requests.
  ✗ Switching models (caches are per-model).
  ✗ Non-deterministic JSON serialization in tool definitions.

Compared to Anthropic: with OpenAI you NEVER need to manually mark cache
breakpoints. The trade-off is less control — you can't pin specific
segments to be cached, you just structure your prompt so the natural prefix
is cacheable.
""")
